# Site settings
title: sfanxiang's blog
email: sfanxiang@gmail.com
description: >-
  Xiang Fan
baseurl: "/"
url: "https://sfanxiang.github.io"
github_username: sfanxiang

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
