# Site settings
title: GSoC 2019 Blogs
email: sfanxiang@gmail.com
description: >-
  Xiang Fan
baseurl: "/"
url: "https://sfanxiang.github.io/gsoc-2019"
github_username: sfanxiang

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
